# version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpg_ai_server
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - NODE_ENV=production

      # AI Providers
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AI_PROVIDER=${AI_PROVIDER}

      # AWS Claude
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_CLAUDE_MODEL=${AWS_CLAUDE_MODEL}
      - USE_AWS_CLAUDE=${USE_AWS_CLAUDE}

      # Proxy (optional)
      - USE_PROXY=${USE_PROXY}
      - PROXY_URL=${PROXY_URL}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}

      # Crawler configs
      - SAVE_SCREENSHOTS=${SAVE_SCREENSHOTS}
      - SCREENSHOT_PATH=${SCREENSHOT_PATH}
      - NAVIGATION_TIMEOUT=${NAVIGATION_TIMEOUT}
      - MAX_RETRIES=${MAX_RETRIES}
      - USER_AGENT=${USER_AGENT}
      - MAX_CONCURRENT_TASKS=${MAX_CONCURRENT_TASKS}
      - QUEUE_RETRY_DELAY=${QUEUE_RETRY_DELAY}

    volumes:
      - ./logs:/app/logs
    restart: always
    networks:
      - cpg-network

volumes:
  mongodb_data:

networks:
  cpg-network:
    driver: bridge
